stages:
  - iosBuild
  - androidAssembleRelease

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

.development-job:
  rules:
    - if: $CI_COMMIT_BRANCH
      when: always

trigger_ios_build:
  stage: iosBuild
  image: curlimages/curl:latest
  before_script: []
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master"'
      when: always
    - if: $CI_COMMIT_BRANCH
      when: manual
  script:
    - echo "Отправляем запрос в Codemagic на сборку ветки $CI_COMMIT_BRANCH..."
    - |
      curl -s -X POST https://api.codemagic.io/builds \
      -H "Content-Type: application/json" \
      -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
      -d '{
        "appId": "69bc0aad1fa59f10af9ed361",
        "workflowId": "ios-debug-build",
        "branch": "'"$CI_COMMIT_BRANCH"'"
      }'
    - echo "Успешно! Билд в Codemagic запущен."

androidAssembleRelease:
  image: fabernovel/android:api-35-gcloud-v1.9.0
  extends: .development-job
  stage: androidAssembleRelease
  script:
    - ./gradlew :app:assembleRelease --no-daemon
    - ./gradlew :app:bundleRelease --no-daemon
  artifacts:
    name: "release-artifacts"
    expire_in: 1 week
    paths:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/bundle/release/*.aab