stages:
  - androidBuildDebug
  - androidLint
  - androidTest
  - androidAssembleRelease

before_script:
  - chmod +x gradlew
  # set gradle folder in project dir so that we can cache it
  # https://stackoverflow.com/questions/34162120/gitlab-ci-gradle-dependency-cache
  - export GRADLE_USER_HOME=`pwd`/.gradle

# cache dependencies
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# template for jobs that are needed during the development process.!reference:
# They run on each commit to the develop branch and in non-draft merge requests
.development-job:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_DRAFT == "false"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - when: never

androidBuildDebug:
  image: fabernovel/android:api-35-gcloud-v1.9.0
  extends: .development-job
  stage: androidBuildDebug
  script:
    - ./gradlew :composeApp:assembleDebug --no-daemon
  artifacts:
    name: "$CI_JOB_NAME-artifacts"
    expire_in: 1 day
    access: none
    paths:
      - composeApp/build/

androidTest:
  image: fabernovel/android:api-35-gcloud-v1.9.0
  extends: .development-job
  stage: androidTest
  needs:
    - androidBuildDebug
  dependencies:
    - androidBuildDebug
  script:
    - ./gradlew :composeApp:testDebugUnitTest --no-daemon

androidAssembleRelease:
  image: fabernovel/android:api-35-gcloud-v1.9.0
  extends: .development-job
  stage: androidAssembleRelease
  needs:
    - androidBuildDebug
    #- androidLint
    - androidTest
  script:
    - ./gradlew :composeApp:assembleRelease --no-daemon
  artifacts:
    paths:
      - composeApp/build/outputs/apk/release/*.apk