stages:
  - androidBuildDebug
  - androidLint
  - androidTest
  - androidAssembleRelease

before_script:
  - chmod +x gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

.development-job:
  rules:
    - if: $CI_COMMIT_BRANCH
      when: always

androidBuildDebug:
  image: fabernovel/android:api-35-gcloud-v1.9.0
  extends: .development-job
  stage: androidBuildDebug
  script:
    - ./gradlew :app:bundleDebug --no-daemon
    - ./gradlew :app:assembleDebug --no-daemon
  artifacts:
    name: "$CI_JOB_NAME-artifacts"
    expire_in: 1 day
    access: none
    paths:
      - app/build/

androidTest:
  image: fabernovel/android:api-35-gcloud-v1.9.0
  extends: .development-job
  stage: androidTest
  needs:
    - androidBuildDebug
  dependencies:
    - androidBuildDebug
  script:
    - ./gradlew :app:testDebugUnitTest --no-daemon

androidAssembleRelease:
  image: fabernovel/android:api-35-gcloud-v1.9.0
  extends: .development-job
  stage: androidAssembleRelease
  needs:
    - androidBuildDebug
    - androidTest
  script:
    - ./gradlew :app:assembleRelease --no-daemon
  artifacts:
    paths:
      - app/build/outputs/apk/release/*.apk
