workflows:
  ios-debug-build:
    name: iOS Debug
    instance_type: mac_mini_m1

    environment:
      xcode: 16.4
      java: 17
      cocoapods: default

    scripts:
      - name: Full iOS Build Setup & Execution
        script: |
          set -e
          
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          
          chmod +x gradlew
          ./gradlew clean --no-daemon 
          ./gradlew :app:generateDummyFramework --no-daemon
          
          cd iosApp
          rm -rf Pods
          pod install
          
          xcodebuild clean build \
            -workspace iosApp.xcworkspace \
            -scheme iosApp \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            COMPILER_INDEX_STORE_ENABLE=NO

    artifacts:
      - iosApp/build/Build/Products/Debug-iphonesimulator/*.app