source 'https://cdn.cocoapods.org'

platform :ios, '15.0'

target 'iosApp' do
  use_frameworks!

  pod 'app', :path => '../app'

  pod 'StripePaymentSheet'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseMessaging'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end
